### ISSUE TITLE
Offer as API and npm package

### ISSUE THREAD

**Issue by radman-x** [ppipada/vscode-flexigpt#2]
Nice work on this code.

It would also be nice to see this offered as a standalone GPT+others API in an npm package. Similar to the (now tired) https://github.com/transitive-bullshit/chatgpt-api.

**Comment by ppipada** [comment]
@radman-x Thanks for your comment. 
I am still in the process of adding some functionality that I think is core to what I want to achieve. Adding preprocessors and cohere support being the important ones. Once that is done, I would explore on publishing a npm package out of this.

**Comment by radman-x** [comment]
👍
