### ISSUE TITLE
Some OpenAI requestParams in prompt file which are 0 are failing to get picked up

### ISSUE THREAD

**Issue by radman-x** [ppipada/vscode-flexigpt#3]
Eg., the following prompt does not pick up and honor the frequencyPenalty nor the presencePenalty being 0:

module.exports = {
    commands: [
        {
            name: "Test cmd",
            template: `Explain following code.
            code:
            {system.selection}`,
            description: "Explain the code",
            requestparams: {
                temperature: 0.6,
                maxTokens: 256,
                topP: 1,
                frequencyPenalty: 0,    // THIS FAILS TO GET USED SINCE IT'S ZERO!
                presencePenalty: 0      // --ditto--
            },
        }
    ],
}

I think the problem is in openaiapi.ts checkAndPopulateCompletionParams() in these lines (actually the presencePenalty will work since it's default value is 0.0 but it would fail if the default value where anything else; and frequencyPenalty line does fail):

     presencePenalty: (inputParams?.presencePenalty as number) || 0.0,
     frequencyPenalty: (inputParams?.frequencyPenalty as number) || 0.5,

I also think there are quite a few other uses of the TS ? operator in this function (and elsewhere) that would fail if the inputParams property is zero.

**Comment by ppipada** [comment]
Thank you for the report. This should be fixed now. Added some tests too. Version 0.7.1
