### ISSUE TITLE
Allow for local Huggingface endpoints

### ISSUE THREAD

**Issue by CalabiYau14** [ppipada/vscode-flexigpt#4]
Wow just found this incredible project. This looks super cool!

The only thing I am missing currently is the possibility of using local Huggingface models. Currently it looks to me, that the you can just configure the name of the model and the URL is automatically being build (e.g. prepending the huggingface url)

Would it be possible to also allow for a generic URL?

Thanks in advance and cheers!

**Comment by ppipada** [comment]
@CalabiYau14 Thanks for your comment.

Just to clarify:
Are you looking for URL to be specified in the huggingface inference api itself? 
> If yes, can you please give a example of how the request would look like, a curl command or general api info should be good enough. 

or
Are you looking for support of open models that can be run offline as gglml or gtqa (like llambda 2 via llama.cpp, etc)?
> I am going to do this very soon.

**Comment by CalabiYau14** [comment]
Hi @ppipada 

thanks for your fast reply! Very much appreciated

I would be looking for option 1). Eg. working with a model which is locally deployed on a server and respects Huggingface's API. Instead of making a call to

`https://api-inference.huggingface.co/models/MODEL_ID`

I would like to be able to make a call to e.g.

'https://MY-OWN-URL/starcoder'

where the endpoint provides the same methods as the original Huggingface API

Hope this is understandable :-)

where the endpoint

**Comment by ppipada** [comment]
Cool.

Noting the below points on gaps I had mentioned:

- Now you can query Llama.cpp directly (+ the previous via openai custom endpoint like the hugging face one)
- Discovering whether a model is chat or not is handled in strategy specific way: hugging face provides uses the getModel api and associated "conversation" tag, open ai uses it for gpt3.5/4 by default. anthropic is default chat only, googles model names have chat as a suffix. Not planning to take any further model info now.
- provider can be provided in requestparams and that will be honored for that prompt.

Pending:
way to switch models mid conversation or continue with the model that was last used/switched to via custom prompt <currently, non prompt chats use the "defaultProvider"s default model>
